//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolynomialWcfClient.PolynomialServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="PolynomialServiceReference.IPolynomial")]
    public interface IPolynomial {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IPolynomial/GetPolynomialSolution", ReplyAction="http://Microsoft.ServiceModel.Samples/IPolynomial/GetPolynomialSolutionResponse")]
        string GetPolynomialSolution(string equation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IPolynomial/GetPolynomialSolution", ReplyAction="http://Microsoft.ServiceModel.Samples/IPolynomial/GetPolynomialSolutionResponse")]
        System.Threading.Tasks.Task<string> GetPolynomialSolutionAsync(string equation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolynomialChannel : PolynomialWcfClient.PolynomialServiceReference.IPolynomial, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolynomialClient : System.ServiceModel.ClientBase<PolynomialWcfClient.PolynomialServiceReference.IPolynomial>, PolynomialWcfClient.PolynomialServiceReference.IPolynomial {
        
        public PolynomialClient() {
        }
        
        public PolynomialClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolynomialClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolynomialClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolynomialClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPolynomialSolution(string equation) {
            return base.Channel.GetPolynomialSolution(equation);
        }
        
        public System.Threading.Tasks.Task<string> GetPolynomialSolutionAsync(string equation) {
            return base.Channel.GetPolynomialSolutionAsync(equation);
        }
    }
}
